apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  creationTimestamp: null
  name: dependant-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DependantService
      name: dependantservices.dependant.example.com
      version: v1alpha1
  description: Placeholder description
  displayName: Dependant Operator
  install:
    spec:
      deployments:
      - name: dependant-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: dependant-operator
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                name: dependant-operator
            spec:
              containers:
              - command:
                - dependant-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: dependant-operator
                image: jarifibrahim/dependant-operator.0.1.0
                imagePullPolicy: Always
                name: dependant-operator
                resources: {}
              serviceAccountName: dependant-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - dependant.example.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: dependant-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
